"""
Exercise 18 (and Solution)
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a “cow”.
For every digit the user guessed correctly in the wrong place is a “bull.”
Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number: 1234
  2 cows, 0 bulls
  Enter a number: 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""
import random
number_to_guess = [random.randint(1, 9) for _ in range(0, 4)]
number_to_guess_int = [str(x) for x in number_to_guess]
number_to_guess_int = int(''.join(number_to_guess_int))
attempts = 0

while True:
    cows, bulls = 0, 0
    attempts += 1
    int_guessed = input('enter your guess for the number: ')
    if int(int_guessed) == number_to_guess_int:
        break
    else:
        for idx, x in enumerate(int_guessed):
            if int(x) == number_to_guess[idx]:
                cows += 1
            else:
                bulls += 1
        print("You have {} cows and {} bulls.".format(cows, bulls))
print("the number was: {} you took {} attempts.".format(number_to_guess, attempts))
